package command;

public enum CommandType {
    CREATE_PATIENT,
    CREATE_DOCTOR,
    CREATE_RECEPTION,
    REMOVE_PATIENT,
    REMOVE_DOCTOR,
    REMOVE_RECEPTION,
    WRITE_ALL_PATIENTS,
    WRITE_ALL_RECEPTIONS,
    WRITE_ALL_DOCTORS,
    CHANGE_NAME,
    CHANGE_STATUS,
    EXIT,
    UNDEFINED
}
